version: '3.8'

services:
  db:
    image: postgres:12.3
    container_name: noah-db-env
    build:
      context: .
      dockerfile: DockerFile.database
      network: host
    user: root
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    volumes: 
      - ./DB:/var/lib/postgresql/data:Z


  jupyter-session-1:
    build: 
      context: .
      dockerfile: DockerFile.jupyter
    image: noah-notebook
    container_name: noah-notebook-env-1
    ports:
      - "8899:8888"
    volumes:
      - ./:/notebooks
      - ${GEEE_STORAGE_DIR}:${GEEE_STORAGE_DIR}:Z
    env_file:
      - .env
    environment:
      - EE_PROJECT_NAME
      - GEEE_STORAGE_DIR
      - NOAH_MINI_DIR
      - ECCC_DATA_DIR
      - SANFI_STORAGE_DIR
      - LANDSAT8_DATA_STORAGE_DIR
      - JUPYTER_TOKEN
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
