FROM jupyter/base-notebook:latest

WORKDIR /notebooks

COPY requirements.txt requirements.txt

# install packages 
# RUN pip install --no-cache-dir -r requirements.txt
# for a fast run restart if you are not updatnig requirements
RUN pip install -r requirements.txt
