FROM postgres:12.3

# add env
ENV PGDATA="/var/lib/postgresql/data/pgdata"

# apt-get install
RUN apt-get update \
    && apt-get install wget -y \
    && apt-get install postgresql-12-postgis-3 -y 
    
COPY ./db.sql /docker-entrypoint-initdb.d/
